version: '3.3'

services:
  sync:
    build: .
    image: zg-scan:latest
    command: sync
    restart: unless-stopped
    environment:
      - ZEROG_STORAGE_LOG_LEVEL=info
    network_mode: host
    container_name: zerog-storage-sync

  stat:
    image: zg-scan:latest
    command: stat
    restart: unless-stopped
    environment:
      - ZEROG_STORAGE_LOG_LEVEL=info
    network_mode: host
    container_name: zerog-storage-stat

  api:
    image: zg-scan:latest
    command: api
    restart: unless-stopped
    environment:
      - ZEROG_STORAGE_LOG_LEVEL=info
      - ZEROG_STORAGE_API_ENDPOINT=:16451
    network_mode: host
    container_name: zerog-storage-api
